### ISSUE TITLE
Daily Aggregate Compression in Redshift

### ISSUE THREAD

**Issue by tspurway** [mozilla/infernyx#10]
Right now we write data to Redshift quite often.  This gives us great latency (freshness), but also increases storage requirements due to low aggregation.  This increases the price of the Redshift instance as well as reduce query performance.

We can introduce a daily job in Infernyx that 'compresses' the data by writing a single row for each unique key per day, and cleaning out the existing day's data.

**Comment by ncloudioj** [comment]
Fixed in c1e2643f1ffac668b568f0af765b23eb115e4f4f
